### ISSUE TITLE
Custom element doesn't exist: layout-card-griddier.

### ISSUE THREAD

**Issue by reins5** [NdR91/NdR-FloorplanUI#1]
Salve 
non riesco a caricare questa card
sai se ci sono problemi o mi puoi indicare eventuali trucchi.
Grazie

**Comment by NdR91** [comment]
Ciao, la card "layout-card-griddier" era un fork dell'ufficiale "Layout Card".

In ogni caso, il "problema" è stato risolto con la totale revisione del codice che l'ha eliminata.
