### ISSUE TITLE
 custom Cards

### ISSUE THREAD

**Issue by reins5** [NdR91/NdR-FloorplanUI#2]
ma le custom Cards in quale file le indichi, tipo:
resources:
  - url: /local/button-card.js
    type: module

Grazie

**Comment by NdR91** [comment]
Ciao! Puoi usare "Plance di lovelace --> Risorse" ed aggiungerle da li.

Però nel 99% dei casi, se installi da HACS, fa tutto lui!

![Schermata 2021-04-16 alle 19 29 13](https://user-images.githubusercontent.com/52299148/115061965-13673980-9eea-11eb-9a03-dd06c4b3672e.jpg)

**Comment by reins5** [comment]
si in effetti HACS lo installa ma in quale file lo richiami, solitamente nel file ui-lovelace.yaml si mette il link:
resources:
  - url: /local/community/button-card/button-card.js
    type: module

ma tu nel file di esempio dove lo metti.

grazie

**Comment by NdR91** [comment]
No, lo richiami solo se installi manualmente. Se usi HACS non è necessario, ecco perchè da me non lo trovi.

**Comment by reins5** [comment]
mah, prima non era così

https://indomus.it/guide/installare-e-configurare-button-card-su-lovelace-ui-di-home-assistant/

**Comment by NdR91** [comment]
Tempo fa non era così, infatti potevi aggiungerlo dove ho fatto lo screen prima io.

In ogni caso, il vantaggio di farlo in "Plance di Lovelace, Ricorse" è che poi non devi richiamare il modulo in ogni singola Dashboard.
